stages:
  get_data:
    cmd: python model-training/restaurant_sentiment/get_data.py
    deps:
    - model-training/restaurant_sentiment/get_data.py
    outs:
    - data/RestaurantReviews_HistoricDump.tsv

  preprocess:
    cmd: python model-training/restaurant_sentiment/preprocess.py
    deps:
    - data/RestaurantReviews_HistoricDump.tsv
    - model-training/restaurant_sentiment/preprocess.py
    outs:
    - data/corpus.pkl
    - data/labels.pkl
    
  train:
    cmd: python model-training/restaurant_sentiment/train.py
    deps:
    - data/corpus.pkl
    - data/labels.pkl
    - model-training/restaurant_sentiment/train.py
    outs:
    - data/X_test.pkl
    - data/X_train.pkl
    - data/y_test.pkl
    - data/y_train.pkl
    - model/bow.pkl
    - model/model.pkl
