name: Pre-release

on:
  workflow_run:
    workflows: ["Test and Quality metrics"]
    types:
      - completed

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    steps:
      - name: Print tag info
        run: echo "Triggered by tag ${{ github.event.workflow_run.head_branch }}"

  train-and-prerelease:
    needs: check-tag
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    permissions:
      contents: write
    env:
      version: ${{ github.event.workflow_run.head_branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download dataset
        run: python model-training/restaurant_sentiment/get_data.py

      - name: Preprocess data
        run: python model-training/restaurant_sentiment/preprocess.py

      - name: Train model
        run: python model-training/restaurant_sentiment/train.py

      - name: Tag pre-release commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          MAIN_SHA=$(git rev-parse origin/main)
          git tag v${{ env.version }} $MAIN_SHA
          git push origin v${{ env.version }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          prerelease: true

      - name: Upload BoW vectorizer model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/bow.pkl
          asset_name: bow-v${{ env.version }}.pkl
          tag: v${{ env.version }}

      - name: Upload model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/model.pkl
          asset_name: model-v${{ env.version }}.pkl
          tag: v${{ env.version }}