name: Pre-release

on:
  push:
    branches:
        main
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  train-and-prerelease:
    runs-on: ubuntu-24.04
    
    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "triggered_by=tag" >> $GITHUB_OUTPUT
          else
            echo "triggered_by=branch" >> $GITHUB_OUTPUT
          fi

      - name: Get latest tag from history
        if: steps.trigger.outputs.triggered_by == 'branch'
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get latest tag from pushed tag
        if: steps.trigger.outputs.triggered_by == 'tag'
        run: |
          LATEST_TAG=${GITHUB_REF:11}
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Calculate pre-release version
        run: |
          VERSION=${latest_tag#v}
          VERSION=${VERSION%%-pre*}
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          if [[ "${{ steps.trigger.outputs.triggered_by }}" == "tag" ]]; then
            PATCH=$((PATCH + 1))
          fi
          DATETIME=$(date +%Y%m%d.%H%M%S)
          NEW_VERSION="$MAJOR.$MINOR.$PATCH-pre.$DATETIME"
          echo "version=$NEW_VERSION"  >> $GITHUB_ENV

      - name: Setup dvc-gs credentials
        env: 
          SERVICE_ACCOUNT_SECRET: ${{ secrets.GSKEYFILE }}
        run: |
          echo "$SERVICE_ACCOUNT_SECRET" > keyfile.json

      - name: dvc-pull data
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json
        run: |
          dvc pull

      - name: Run DVC pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json
        run: dvc repro

      - name: Tag pre-release commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          MAIN_SHA=$(git rev-parse origin/main)
          git tag v${{ env.version }} $MAIN_SHA
          git push origin v${{ env.version }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          prerelease: true

      - name: Upload BoW vectorizer model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/bow.pkl
          asset_name: bow-v${{ env.version }}.pkl
          tag: v${{ env.version }}

      - name: Upload model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/model.pkl
          asset_name: model-v${{ env.version }}.pkl
          tag: v${{ env.version }}