name: Pre-release

on:
  push:
    branches:
        main
    tags-ignore:
      - '**'
  
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  train-and-prerelease:
    runs-on: ubuntu-24.04
    
    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Determine trigger type
        id: trigger
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ] && [ "${{ github.event.workflow }}" == "Release" ]; then
            echo "triggered_by=release" >> $GITHUB_OUTPUT
          else
            echo "triggered_by=push" >> $GITHUB_OUTPUT

      - name: Get latest tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV
      
      - name: Parse version from tag (if triggered by tag)
        if: steps.trigger.outputs.triggered_by == 'release'
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Calculate pre-release version
        if: steps.trigger.outputs.triggered_by == 'push'
        run: |
          VERSION=${latest_tag#v}
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          PATCH=$((PATCH + 1))
          DATETIME=$(date +%Y%m%d.%H%M%S)
          NEW_VERSION="$MAJOR.$MINOR.$PATCH-pre.$DATETIME"
          echo "version=$NEW_VERSION"  >> $GITHUB_ENV

      - name: Download dataset
        run: python model-training/restaurant_sentiment/get_data.py

      - name: Preprocess data
        run: python model-training/restaurant_sentiment/preprocess.py

      - name: Train model
        run: python model-training/restaurant_sentiment/train.py

      - name: Tag pre-release commit
        if: steps.trigger.outputs.triggered_by == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ env.version }}
          git push origin v${{ env.version }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          prerelease: true

      - name: Upload BoW vectorizer model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/bow.pkl
          asset_name: bow-v${{ env.version }}.pkl
          tag: v${{ env.version }}

      - name: Upload model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/model.pkl
          asset_name: model-v${{ env.version }}.pkl
          tag: v${{ env.version }}