name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  train-and-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup dvc
        uses: iterative/setup-dvc@v1
        with:
          version: '3.59.2'
        continue-on-error: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Parse version from tag
        run: |
          VERSION=${GITHUB_REF:11}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Setup dvc-gs credentials
        env: 
          SERVICE_ACCOUNT_SECRET: ${{ secrets.GSKEYFILE }}
        run: |
          echo "$SERVICE_ACCOUNT_SECRET" > keyfile.json

      - name: dvc-pull data
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json
        run: |
          dvc pull

      - name: Run DVC pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json
        run: dvc repro

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          generate_release_notes: true

      - name: Upload BoW vectorizer model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/bow.pkl
          asset_name: bow-v${{ env.version }}.pkl
          tag: v${{ env.version }}

      - name: Upload model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/model.pkl
          asset_name: model-v${{ env.version }}.pkl
          tag: v${{ env.version }}