name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check test workflow status for this commit
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.GITHUB_REF.split('/').pop();
            const { data: tagData } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${tag}`
            });
            const commitSha = tagData.object.sha;
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 20
            });
            const testRun = runs.workflow_runs.find(run =>
              run.name === 'Test and Quality metrics' && run.head_sha === commitSha
            );
            if (!testRun) {
              core.setFailed('No test workflow run found for this commit.');
            } else if (testRun.conclusion !== 'success') {
              core.setFailed(`Test workflow did not succeed (status: ${testRun.conclusion}). Release aborted.`);
            }

  train-and-release:
    runs-on: ubuntu-24.04
    needs: check-tests
    env:
      version: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download dataset
        run: python model-training/restaurant_sentiment/get_data.py

      - name: Preprocess data
        run: python model-training/restaurant_sentiment/preprocess.py

      - name: Train model
        run: python model-training/restaurant_sentiment/train.py

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          generate_release_notes: true

      - name: Upload BoW vectorizer model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/bow.pkl
          asset_name: bow-v${{ env.version }}.pkl
          tag: v${{ env.version }}

      - name: Upload model
        uses: svenstaro/upload-release-action@v2
        with: 
          file: model/model.pkl
          asset_name: model-v${{ env.version }}.pkl
          tag: v${{ env.version }}